### ISSUE TITLE
Astro Icons are invisible

### ISSUE THREAD

**Issue by esalberg100** [RocketCommunicationsInc/astro-uxds#187]
The Astro icons component doesn't work in any capacity, for example if starting with the astro-boilerplate-react and adding a notification, the "x" close icon will not show, nor will any other icon added to buttons. Using Inspect Element, I can verify that the element is in fact there, and it takes up space, but it is not visible. Fix is needed immediately.

**Comment by markacianfrani** [comment]
@esalberg100 thanks for reporting this! this has been hotfixed. please let us know if you're still having issues over at the [astro-components](https://github.com/RocketCommunicationsInc/astro-components) repo
